import type { PressQuestion } from '../types/PressConference';

/**
 * Banco amplo de coletivas.
 * Cada pergunta tem ≥4 opções com intenções distintas
 * (agradar torcida / diretoria / elenco / mídia / provocação / cautela).
 */
export const PRESS_QUESTIONS: PressQuestion[] = [
  // ═══ PRÉ — gerais ══════════════════════════════════════════════════════════
  {
    id: 'pre_expectativa',
    context: 'pre_match',
    weight: 2,
    prompt: 'O que o senhor espera deste jogo?',
    options: [
      { id: 'a', label: 'Vamos para cima — merecemos os três pontos.', effects: { supporterConfidence: 5, squadMorale: 3, boardConfidence: 1, mediaConfidence: -1 }, headlineHint: 'técnico confiante antes do jogo' },
      { id: 'b', label: 'Respeito total ao adversário; um jogo de cada vez.', effects: { supporterConfidence: 1, squadMorale: 1, boardConfidence: 3, mediaConfidence: 2 }, headlineHint: 'técnico pede cautela e respeito' },
      { id: 'c', label: 'A cobrança é justa — temos obrigação de vencer.', effects: { supporterConfidence: 3, squadMorale: -2, boardConfidence: 3, mediaConfidence: 1 }, headlineHint: 'técnico assume pressão' },
      { id: 'd', label: 'Não falo de placar. Foco no trabalho e ponto.', effects: { supporterConfidence: -2, squadMorale: 2, boardConfidence: 1, mediaConfidence: -2 }, headlineHint: 'técnico evita falar em resultado' },
    ],
  },
  {
    id: 'pre_elenco',
    context: 'pre_match',
    weight: 2,
    prompt: 'O elenco está preparado mentalmente?',
    options: [
      { id: 'a', label: 'O grupo está unido e focado.', effects: { squadMorale: 5, supporterConfidence: 2, mediaConfidence: 1 }, headlineHint: 'técnico exalta união do elenco' },
      { id: 'b', label: 'Alguns precisam render mais — cobrei isso no CT.', effects: { squadMorale: -3, boardConfidence: 4, supporterConfidence: 1, mediaConfidence: 2 }, headlineHint: 'técnico cobra rendimento interno' },
      { id: 'c', label: 'Lidamos com desfalques, mas o plano está pronto.', effects: { squadMorale: 2, boardConfidence: 2, mediaConfidence: 1 }, headlineHint: 'técnico fala em desfalques sem drama' },
      { id: 'd', label: 'Quem não está 100% fica de fora. Simples.', effects: { squadMorale: -2, boardConfidence: 3, mediaConfidence: -1 }, headlineHint: 'técnico endurece critério de convocação' },
    ],
  },
  {
    id: 'pre_adversario',
    context: 'pre_match',
    weight: 1.5,
    prompt: 'Como avalia o adversário?',
    options: [
      { id: 'a', label: 'Time perigoso; vamos ter de ser inteligentes.', effects: { boardConfidence: 2, squadMorale: 1, mediaConfidence: 2 }, headlineHint: 'técnico respeita o rival' },
      { id: 'b', label: 'Eles que se preocupem conosco.', effects: { supporterConfidence: 6, squadMorale: 3, boardConfidence: -1, mediaConfidence: -2 }, headlineHint: 'técnico provoca o adversário' },
      { id: 'c', label: 'Analisamos o que precisávamos. Sem novela.', effects: { boardConfidence: 1, mediaConfidence: -1 }, headlineHint: 'técnico evita guerra de declarações' },
      { id: 'd', label: 'São favoritos na imprensa — ótimo, a pressão é deles.', effects: { squadMorale: 2, supporterConfidence: 2, mediaConfidence: -3 }, headlineHint: 'técnico rebate favoritismo da mídia' },
    ],
  },
  {
    id: 'pre_torcida',
    context: 'pre_match',
    weight: 2,
    prompt: 'Mensagem para a torcida?',
    options: [
      { id: 'a', label: 'Precisamos de vocês do 1º ao último minuto.', effects: { supporterConfidence: 7, squadMorale: 2, mediaConfidence: 1 }, headlineHint: 'técnico pede apoio da arquibancada' },
      { id: 'b', label: 'Confiança no trabalho — resultados vêm.', effects: { supporterConfidence: 2, boardConfidence: 3, mediaConfidence: 1 }, headlineHint: 'técnico pede paciência' },
      { id: 'c', label: 'Torcida cobra, nós trabalhamos. Simples.', effects: { supporterConfidence: -4, boardConfidence: 1, squadMorale: 1, mediaConfidence: -1 }, headlineHint: 'técnico responde frio à cobrança' },
      { id: 'd', label: 'Quem vibrar junto, vibra com a gente. Quem vaiar, atrapalha.', effects: { supporterConfidence: -2, squadMorale: 3, mediaConfidence: -3 }, headlineHint: 'técnico critica possíveis vaias' },
    ],
  },
  {
    id: 'pre_midia_hostil',
    context: 'pre_match',
    weight: 2.2,
    tags: { mediaMax: 40 },
    prompt: 'A imprensa tem sido dura com o clube. Responde?',
    options: [
      { id: 'a', label: 'Respeito o trabalho de vocês; discordamos do tom.', effects: { mediaConfidence: 3, boardConfidence: 2, supporterConfidence: 1 }, headlineHint: 'técnico tenta apaziguar a imprensa' },
      { id: 'b', label: 'Quem não está no dia a dia fala fácil.', effects: { mediaConfidence: -5, squadMorale: 3, supporterConfidence: 2 }, headlineHint: 'técnico rebate a imprensa' },
      { id: 'c', label: 'Prefiro que julguem o que acontece em campo.', effects: { mediaConfidence: 1, boardConfidence: 1 }, headlineHint: 'técnico pede julgamento só em campo' },
      { id: 'd', label: 'Alguns precisam de manchete — nós precisamos de pontos.', effects: { mediaConfidence: -4, boardConfidence: 2, supporterConfidence: 3 }, headlineHint: 'técnico acusa imprensa de sensacionalismo' },
    ],
  },
  {
    id: 'pre_moral_baixa',
    context: 'pre_match',
    weight: 2.5,
    tags: { avgMoraleMax: 45 },
    prompt: 'Há boatos de clima pesado no elenco. Confirma?',
    options: [
      { id: 'a', label: 'Estamos juntos. Conversa interna, solução interna.', effects: { squadMorale: 4, mediaConfidence: -1, boardConfidence: 1 }, headlineHint: 'técnico nega crise no vestiário' },
      { id: 'b', label: 'Sim, cobrei postura. Quem não topa o padrão, senta.', effects: { squadMorale: -2, boardConfidence: 4, mediaConfidence: 2 }, headlineHint: 'técnico admite cobrança dura' },
      { id: 'c', label: 'Boato. Próxima pergunta.', effects: { mediaConfidence: -3, supporterConfidence: -1, squadMorale: 1 }, headlineHint: 'técnico corta especulação' },
      { id: 'd', label: 'O grupo precisa de apoio, não de fofoca.', effects: { squadMorale: 3, supporterConfidence: 2, mediaConfidence: -2 }, headlineHint: 'técnico pede apoio e critica fofoca' },
    ],
  },
  {
    id: 'pre_seca_ataque',
    context: 'pre_match',
    weight: 2.8,
    tags: { requiresFormDry: true },
    prompt: 'A torcida cobra o ataque sem gols. O que diz do artilheiro em jejum?',
    options: [
      { id: 'a', label: 'Confio nele. Gol é consequência do trabalho.', effects: { squadMorale: 4, supporterConfidence: 1, mediaConfidence: 1 }, headlineHint: 'técnico banca atacante em jejum' },
      { id: 'b', label: 'Precisa render mais — cobrei isso ontem.', effects: { squadMorale: -3, boardConfidence: 2, supporterConfidence: 2, mediaConfidence: 2 }, headlineHint: 'técnico cobra atacante seco' },
      { id: 'c', label: 'O time marca, não só um nome.', effects: { squadMorale: 2, supporterConfidence: -1, mediaConfidence: -1 }, headlineHint: 'técnico dilui cobrança no coletivo' },
      { id: 'd', label: 'Vocês já decidiram a narrativa; eu decido a escalação.', effects: { mediaConfidence: -5, squadMorale: 2, boardConfidence: 1 }, headlineHint: 'técnico confronta narrativa da mídia' },
    ],
  },
  {
    id: 'pre_crise_sequencia',
    context: 'pre_match',
    weight: 2.6,
    tags: { recentLossesMin: 2 },
    prompt: 'Sequência ruim. Teme pelo cargo?',
    options: [
      { id: 'a', label: 'Trabalho. Resultados voltam com trabalho.', effects: { boardConfidence: 2, mediaConfidence: 1, squadMorale: 2 }, headlineHint: 'técnico evita falar em demissão' },
      { id: 'b', label: 'Quem decide meu futuro é a diretoria, não a coletiva.', effects: { boardConfidence: 3, mediaConfidence: -2 }, headlineHint: 'técnico devolve pressão à diretoria' },
      { id: 'c', label: 'Pressão faz parte. O vestiário está comigo.', effects: { squadMorale: 4, supporterConfidence: 2, mediaConfidence: 1 }, headlineHint: 'técnico diz ter apoio do elenco' },
      { id: 'd', label: 'Se alguém quer sangue, procure outro esporte.', effects: { mediaConfidence: -6, supporterConfidence: -2, boardConfidence: -1 }, headlineHint: 'técnico explode com a cobrança' },
    ],
  },
  {
    id: 'pre_classico',
    context: 'pre_match',
    weight: 2.4,
    tags: { significance: ['derby', 'rivalry', 'revenge'] },
    prompt: 'Clássico/rivalidade. Como controla a emoção?',
    options: [
      { id: 'a', label: 'É só futebol — com mais história. Foco tático.', effects: { boardConfidence: 2, squadMorale: 2, mediaConfidence: 1 }, headlineHint: 'técnico resfria o clássico' },
      { id: 'b', label: 'Queremos ganhar esse mais do que qualquer outro.', effects: { supporterConfidence: 6, squadMorale: 3, mediaConfidence: -1 }, headlineHint: 'técnico eleva o tom do clássico' },
      { id: 'c', label: 'Eles que façam provocação; nós fazemos o jogo.', effects: { squadMorale: 3, supporterConfidence: 3, mediaConfidence: 0 }, headlineHint: 'técnico evita guerra verbal' },
      { id: 'd', label: 'A imprensa ama narrativa de ódio. Eu amo três pontos.', effects: { mediaConfidence: -3, boardConfidence: 2, supporterConfidence: 2 }, headlineHint: 'técnico critica cobertura do clássico' },
    ],
  },
  {
    id: 'pre_titulo_rebaixamento',
    context: 'pre_match',
    weight: 2.5,
    tags: { significance: ['title', 'relegation', 'decisive', 'cup_final'] },
    prompt: 'Jogo decisivo. O elenco sente o peso?',
    options: [
      { id: 'a', label: 'Peso vira combustível quando o grupo é maduro.', effects: { squadMorale: 4, boardConfidence: 2, mediaConfidence: 1 }, headlineHint: 'técnico transforma pressão em combustível' },
      { id: 'b', label: 'Trato como jogo normal — senão trava.', effects: { squadMorale: 2, boardConfidence: 1, mediaConfidence: 2 }, headlineHint: 'técnico tenta normalizar decisão' },
      { id: 'c', label: 'É o jogo da temporada. Assumimos.', effects: { supporterConfidence: 4, boardConfidence: 3, squadMorale: 1, mediaConfidence: 0 }, headlineHint: 'técnico assume dimensão do jogo' },
      { id: 'd', label: 'Vocês dramatizam; nós preparamos.', effects: { mediaConfidence: -4, squadMorale: 2 }, headlineHint: 'técnico acusa dramatização da mídia' },
    ],
  },

  // ═══ PÓS — VITÓRIA ═════════════════════════════════════════════════════════
  {
    id: 'post_win_chave',
    context: 'post_match',
    weight: 2,
    tags: { results: ['win'] },
    prompt: 'Qual foi a chave da vitória?',
    options: [
      { id: 'a', label: 'O elenco mereceu — entrega total.', effects: { squadMorale: 6, supporterConfidence: 3, boardConfidence: 2, mediaConfidence: 1 }, headlineHint: 'técnico dedica vitória ao elenco' },
      { id: 'b', label: 'O plano tático funcionou como desenhamos.', effects: { boardConfidence: 4, squadMorale: 2, mediaConfidence: 2 }, headlineHint: 'técnico celebra acerto tático' },
      { id: 'c', label: 'A torcida empurrou o time.', effects: { supporterConfidence: 7, squadMorale: 2, mediaConfidence: 1 }, headlineHint: 'técnico agradece a torcida' },
      { id: 'd', label: 'Quem duvidava pode rever a fita.', effects: { mediaConfidence: -3, supporterConfidence: 3, squadMorale: 2 }, headlineHint: 'técnico ironiza críticas prévias' },
    ],
  },
  {
    id: 'post_win_proximo',
    context: 'post_match',
    weight: 1.8,
    tags: { results: ['win'] },
    prompt: 'Já pensa no próximo compromisso?',
    options: [
      { id: 'a', label: 'Pé no chão. Amanhã é outro jogo.', effects: { boardConfidence: 3, mediaConfidence: 2, squadMorale: 1 }, headlineHint: 'técnico pede pé no chão' },
      { id: 'b', label: 'Hoje a gente merece celebrar um pouco.', effects: { squadMorale: 5, supporterConfidence: 3, boardConfidence: -1, mediaConfidence: -1 }, headlineHint: 'técnico autoriza celebração' },
      { id: 'c', label: 'Queremos mais — a temporada é longa.', effects: { boardConfidence: 2, supporterConfidence: 3, squadMorale: 2, mediaConfidence: 1 }, headlineHint: 'técnico mantém ambição' },
      { id: 'd', label: 'Vou dormir pensando em corrigir detalhes.', effects: { boardConfidence: 3, squadMorale: 0, mediaConfidence: 2 }, headlineHint: 'técnico já mira aperfeiçoamento' },
    ],
  },
  {
    id: 'post_win_goleada',
    context: 'post_match',
    weight: 2.8,
    tags: { results: ['win'], minMargin: 3 },
    prompt: 'Goleada. Foi o jogo perfeito?',
    options: [
      { id: 'a', label: 'Foi uma noite especial. Merecida.', effects: { supporterConfidence: 5, squadMorale: 4, mediaConfidence: 1 }, headlineHint: 'técnico celebra goleada' },
      { id: 'b', label: 'Gostei da atitude; ainda há o que limpar.', effects: { boardConfidence: 3, squadMorale: 2, mediaConfidence: 2 }, headlineHint: 'técnico tempera euforia da goleada' },
      { id: 'c', label: 'Isso silencia muita conversa fiada.', effects: { mediaConfidence: -4, supporterConfidence: 4, squadMorale: 3 }, headlineHint: 'técnico usa goleada contra críticos' },
      { id: 'd', label: 'Placar infla ego. Eu quero consistência.', effects: { boardConfidence: 4, mediaConfidence: 1, squadMorale: 1 }, headlineHint: 'técnico prioriza consistência' },
    ],
  },
  {
    id: 'post_win_hattrick',
    context: 'post_match',
    weight: 3,
    tags: { results: ['win'], requiresHatTrick: true },
    prompt: 'Hat-trick do seu jogador. Como avalia o desempenho dele?',
    options: [
      { id: 'a', label: 'Ele estava com fome de gol. Mereceu a noite.', effects: { squadMorale: 5, supporterConfidence: 4, mediaConfidence: 2 }, headlineHint: 'técnico exalta hat-trick' },
      { id: 'b', label: 'O coletivo criou as condições — ele finalizou.', effects: { squadMorale: 3, boardConfidence: 2, mediaConfidence: 1 }, headlineHint: 'técnico dilui mérito no coletivo' },
      { id: 'c', label: 'Quem pedia a cabeça dele agora aplaude. Futebol.', effects: { mediaConfidence: -3, supporterConfidence: 3, squadMorale: 4 }, headlineHint: 'técnico ironiza cobrança anterior' },
      { id: 'd', label: 'Peço que ele repita a intensidade, não só os gols.', effects: { boardConfidence: 2, squadMorale: 2, mediaConfidence: 2 }, headlineHint: 'técnico cobra continuidade após hat-trick' },
    ],
  },
  {
    id: 'post_win_clean',
    context: 'post_match',
    weight: 2.2,
    tags: { results: ['win'], cleanSheet: true },
    prompt: 'Defesa a zero. Foi prioridade?',
    options: [
      { id: 'a', label: 'Sim. Sem solidariedade atrás, não sobe na tabela.', effects: { boardConfidence: 3, squadMorale: 3, mediaConfidence: 2 }, headlineHint: 'técnico valoriza clean sheet' },
      { id: 'b', label: 'O goleiro e a zaga foram heróis silenciosos.', effects: { squadMorale: 5, supporterConfidence: 2 }, headlineHint: 'técnico exalta setor defensivo' },
      { id: 'c', label: 'Ataque chama atenção; defesa ganha campeonato.', effects: { boardConfidence: 2, mediaConfidence: 1, supporterConfidence: 1 }, headlineHint: 'técnico fala em equilíbrio' },
      { id: 'd', label: 'Quem só olha xG esquece que não levar gol também é arte.', effects: { mediaConfidence: -2, boardConfidence: 2 }, headlineHint: 'técnico critica obsessão por estatística' },
    ],
  },
  {
    id: 'post_win_fora',
    context: 'post_match',
    weight: 2,
    tags: { results: ['win'], locations: ['away'] },
    prompt: 'Vitória fora de casa. Difícil?',
    options: [
      { id: 'a', label: 'Muito. Caráter de time grande.', effects: { supporterConfidence: 5, squadMorale: 4, boardConfidence: 2 }, headlineHint: 'técnico valoriza vitória fora' },
      { id: 'b', label: 'O plano visitante funcionou.', effects: { boardConfidence: 3, mediaConfidence: 2 }, headlineHint: 'técnico aponta plano visitante' },
      { id: 'c', label: 'Silenciamos a casa deles.', effects: { supporterConfidence: 4, mediaConfidence: -1, squadMorale: 3 }, headlineHint: 'técnico provoca a casa adversária' },
      { id: 'd', label: 'Fora ou em casa, a obrigação é a mesma.', effects: { boardConfidence: 2, mediaConfidence: 1 }, headlineHint: 'técnico equaliza cobrança' },
    ],
  },
  {
    id: 'post_win_apos_crise',
    context: 'post_match',
    weight: 2.7,
    tags: { results: ['win'], recentLossesMin: 2 },
    prompt: 'Vitória após sequência ruim. Alívio?',
    options: [
      { id: 'a', label: 'Alívio e confirmação do trabalho.', effects: { boardConfidence: 4, squadMorale: 4, mediaConfidence: 2 }, headlineHint: 'técnico fala em alívio após crise' },
      { id: 'b', label: 'Quem pediu minha cabeça pode respirar… por enquanto.', effects: { mediaConfidence: -4, supporterConfidence: 3, boardConfidence: 1 }, headlineHint: 'técnico ironiza pedidos de demissão' },
      { id: 'c', label: 'O grupo não desistiu. Isso vale ouro.', effects: { squadMorale: 6, supporterConfidence: 3 }, headlineHint: 'técnico exalta resiliência' },
      { id: 'd', label: 'Um resultado não apaga tudo — mas muda a energia.', effects: { boardConfidence: 2, mediaConfidence: 2, squadMorale: 2 }, headlineHint: 'técnico equilibra discurso pós-crise' },
    ],
  },

  // ═══ PÓS — EMPATE ══════════════════════════════════════════════════════════
  {
    id: 'post_draw_leitura',
    context: 'post_match',
    weight: 2,
    tags: { results: ['draw'] },
    prompt: 'Empate justo?',
    options: [
      { id: 'a', label: 'Justo. Podia ser melhor, mas aceitamos o ponto.', effects: { boardConfidence: 1, squadMorale: 1, mediaConfidence: 2 }, headlineHint: 'técnico aceita empate' },
      { id: 'b', label: 'Merecíamos mais — o jogo pediu vitória.', effects: { supporterConfidence: 3, squadMorale: 2, boardConfidence: -1, mediaConfidence: -1 }, headlineHint: 'técnico se queixa do empate' },
      { id: 'c', label: 'Faltou atitude em momentos-chave.', effects: { squadMorale: -3, boardConfidence: 3, mediaConfidence: 2 }, headlineHint: 'técnico critica falta de atitude' },
      { id: 'd', label: 'Empate é o que a mídia chama de “fracasso” quando quer manchete.', effects: { mediaConfidence: -4, boardConfidence: 1, squadMorale: 1 }, headlineHint: 'técnico critica leitura da mídia' },
    ],
  },
  {
    id: 'post_draw_torcida',
    context: 'post_match',
    weight: 2.2,
    tags: { results: ['draw'] },
    prompt: 'A torcida saiu frustrada. O que diz?',
    options: [
      { id: 'a', label: 'Entendo a cobrança; vamos corrigir.', effects: { supporterConfidence: 4, boardConfidence: 1, mediaConfidence: 1 }, headlineHint: 'técnico entende cobrança' },
      { id: 'b', label: 'Quem está aqui dentro sabe o esforço.', effects: { squadMorale: 4, supporterConfidence: -3, mediaConfidence: -1 }, headlineHint: 'técnico defende o elenco' },
      { id: 'c', label: 'Frustração é combustível se for inteligente.', effects: { supporterConfidence: 2, squadMorale: 2, mediaConfidence: 1 }, headlineHint: 'técnico pede cobrança inteligente' },
      { id: 'd', label: 'Vaiar o próprio time ajuda o adversário.', effects: { supporterConfidence: -4, squadMorale: 2, mediaConfidence: -2 }, headlineHint: 'técnico critica vaias' },
    ],
  },
  {
    id: 'post_draw_casa',
    context: 'post_match',
    weight: 2.3,
    tags: { results: ['draw'], locations: ['home'] },
    prompt: 'Empate em casa dói mais. Concorda?',
    options: [
      { id: 'a', label: 'Dói. Casa é obrigação de ousar mais.', effects: { supporterConfidence: 2, boardConfidence: 2, squadMorale: -1, mediaConfidence: 1 }, headlineHint: 'técnico admite dor do empate em casa' },
      { id: 'b', label: 'Um ponto é um ponto. Segue o campeonato.', effects: { boardConfidence: 2, mediaConfidence: 2 }, headlineHint: 'técnico relativiza empate em casa' },
      { id: 'c', label: 'Criamos, não matamos. Isso se treina.', effects: { squadMorale: 1, boardConfidence: 2, mediaConfidence: 1 }, headlineHint: 'técnico aponta falta de eficácia' },
      { id: 'd', label: 'A narrativa de “fracasso em casa” é preguiçosa.', effects: { mediaConfidence: -3, supporterConfidence: -1 }, headlineHint: 'técnico rebela-se contra narrativa' },
    ],
  },

  // ═══ PÓS — DERROTA ═════════════════════════════════════════════════════════
  {
    id: 'post_loss_responsavel',
    context: 'post_match',
    weight: 2.5,
    tags: { results: ['loss'] },
    prompt: 'Onde está a responsabilidade pela derrota?',
    options: [
      { id: 'a', label: 'A responsabilidade é minha. Vou ajustar.', effects: { boardConfidence: 4, squadMorale: 3, supporterConfidence: 2, mediaConfidence: 2 }, headlineHint: 'técnico assume culpa' },
      { id: 'b', label: 'Erros individuais pesaram demais.', effects: { squadMorale: -4, boardConfidence: 1, supporterConfidence: -1, mediaConfidence: 1 }, headlineHint: 'técnico aponta erros individuais' },
      { id: 'c', label: 'Decisões de arbitragem mudaram o jogo.', effects: { supporterConfidence: 3, boardConfidence: -2, mediaConfidence: -2 }, headlineHint: 'técnico critica arbitragem' },
      { id: 'd', label: 'Prefiro analisar com calma antes de falar.', effects: { boardConfidence: 1, mediaConfidence: -2, supporterConfidence: -1 }, headlineHint: 'técnico evita declaração' },
    ],
  },
  {
    id: 'post_loss_vestiario',
    context: 'post_match',
    weight: 2.3,
    tags: { results: ['loss'] },
    prompt: 'Como está o vestiário?',
    options: [
      { id: 'a', label: 'Machucados, mas unidos. Vamos reagir.', effects: { squadMorale: 5, supporterConfidence: 2, boardConfidence: 1, mediaConfidence: 1 }, headlineHint: 'técnico promete reação' },
      { id: 'b', label: 'Conversa dura. Exijo mais.', effects: { squadMorale: -2, boardConfidence: 4, mediaConfidence: 2 }, headlineHint: 'técnico endurece o discurso' },
      { id: 'c', label: 'Confio nestes jogadores. Ponto final.', effects: { squadMorale: 6, boardConfidence: 0, supporterConfidence: 1, mediaConfidence: -1 }, headlineHint: 'técnico renova confiança no elenco' },
      { id: 'd', label: 'Silêncio no vestiário. Trabalho fala amanhã.', effects: { mediaConfidence: -2, boardConfidence: 1 }, headlineHint: 'técnico fecha o vestiário' },
    ],
  },
  {
    id: 'post_loss_humilhacao',
    context: 'post_match',
    weight: 3,
    tags: { results: ['loss'], minMargin: 3 },
    prompt: 'Derrota elástica. Há explicação?',
    options: [
      { id: 'a', label: 'Inaceitável. Assumo e corrijo na base.', effects: { boardConfidence: 3, supporterConfidence: 1, squadMorale: -1, mediaConfidence: 1 }, headlineHint: 'técnico classifica goleada como inaceitável' },
      { id: 'b', label: 'Desmoronamos após o segundo gol. Mentalidade.', effects: { squadMorale: -3, boardConfidence: 2, mediaConfidence: 2 }, headlineHint: 'técnico aponta quebra mental' },
      { id: 'c', label: 'Não vou crucificar jogador em pública.', effects: { squadMorale: 3, mediaConfidence: -1, supporterConfidence: -2 }, headlineHint: 'técnico protege elenco após goleada' },
      { id: 'd', label: 'A festa alheia já começou na imprensa. Nós vamos trabalhar.', effects: { mediaConfidence: -5, boardConfidence: 1, squadMorale: 2 }, headlineHint: 'técnico acusa festa da imprensa' },
    ],
  },
  {
    id: 'post_loss_casa',
    context: 'post_match',
    weight: 2.4,
    tags: { results: ['loss'], locations: ['home'] },
    prompt: 'Perder em casa. Mensagem à torcida?',
    options: [
      { id: 'a', label: 'Peço desculpas. Vamos devolver em campo.', effects: { supporterConfidence: 4, boardConfidence: 1, mediaConfidence: 1 }, headlineHint: 'técnico pede desculpas à torcida' },
      { id: 'b', label: 'Quem ficou até o fim, obrigado. Vocês mereciam mais.', effects: { supporterConfidence: 5, squadMorale: 1 }, headlineHint: 'técnico agradece quem ficou' },
      { id: 'c', label: 'Casa também erra. Assumimos.', effects: { boardConfidence: 2, mediaConfidence: 1 }, headlineHint: 'técnico assume derrota em casa' },
      { id: 'd', label: 'Vaiar no 0x1 não ajuda a virar o jogo.', effects: { supporterConfidence: -5, squadMorale: 2, mediaConfidence: -2 }, headlineHint: 'técnico critica vaias precoces' },
    ],
  },
  {
    id: 'post_loss_vermelho',
    context: 'post_match',
    weight: 2.8,
    tags: { results: ['loss'], requiresRedCard: true },
    prompt: 'A expulsão pesou. Como avalia?',
    options: [
      { id: 'a', label: 'Ingenuidade. Não podemos dar esse presente.', effects: { squadMorale: -3, boardConfidence: 2, mediaConfidence: 1 }, headlineHint: 'técnico critica expulsão' },
      { id: 'b', label: 'O lance foi duvidoso. Mas jogamos com 10.', effects: { supporterConfidence: 2, mediaConfidence: -2, boardConfidence: -1 }, headlineHint: 'técnico questiona vermelho' },
      { id: 'c', label: 'Mesmo com 10, tínhamos de competir melhor.', effects: { boardConfidence: 3, squadMorale: 1, mediaConfidence: 2 }, headlineHint: 'técnico exige mais mesmo com 10' },
      { id: 'd', label: 'Vou falar com o jogador longe do microfone.', effects: { squadMorale: 2, mediaConfidence: -1 }, headlineHint: 'técnico evita crucificar em pública' },
    ],
  },
  {
    id: 'post_loss_crise',
    context: 'post_match',
    weight: 2.8,
    tags: { results: ['loss'], recentLossesMin: 2 },
    prompt: 'Outra derrota. A crise está instalada?',
    options: [
      { id: 'a', label: 'Crise se resolve com trabalho, não com manchete.', effects: { mediaConfidence: -3, boardConfidence: 2, squadMorale: 2 }, headlineHint: 'técnico rejeita narrativa de crise' },
      { id: 'b', label: 'Estamos numa fase ruim. Não nego.', effects: { mediaConfidence: 2, boardConfidence: 1, supporterConfidence: 1 }, headlineHint: 'técnico admite fase ruim' },
      { id: 'c', label: 'O vestiário não entrega a toalha.', effects: { squadMorale: 5, supporterConfidence: 2 }, headlineHint: 'técnico diz que elenco não entrega' },
      { id: 'd', label: 'Se a diretoria quer mudança, que diga a mim — não a vocês.', effects: { boardConfidence: -2, mediaConfidence: -4 }, headlineHint: 'técnico confronta especulação de demissão' },
    ],
  },

  // ═══ BOTH / MÍDIA ══════════════════════════════════════════════════════════
  {
    id: 'both_estilo',
    context: 'both',
    weight: 1.4,
    prompt: 'A imprensa fala do seu estilo de jogo. Comenta?',
    options: [
      { id: 'a', label: 'Temos identidade — não abro mão disso.', effects: { boardConfidence: 2, squadMorale: 2, supporterConfidence: 2, mediaConfidence: 1 }, headlineHint: 'técnico defende identidade' },
      { id: 'b', label: 'Ganhar importa; o estilo se adapta.', effects: { boardConfidence: 3, mediaConfidence: 1 }, headlineHint: 'técnico se diz pragmático' },
      { id: 'c', label: 'Quem não está no dia a dia fala fácil.', effects: { mediaConfidence: -4, squadMorale: 2, supporterConfidence: -1 }, headlineHint: 'técnico rebate crítica tática' },
      { id: 'd', label: 'Aceito debate técnico. Não aceito caricata.', effects: { mediaConfidence: -2, boardConfidence: 1 }, headlineHint: 'técnico pede debate sério' },
    ],
  },
  {
    id: 'both_midia_geral',
    context: 'both',
    weight: 1.8,
    prompt: 'Como está a relação com a imprensa?',
    options: [
      { id: 'a', label: 'Profissional. Cada um faz seu trabalho.', effects: { mediaConfidence: 2, boardConfidence: 1 }, headlineHint: 'técnico mantém tom profissional com a mídia' },
      { id: 'b', label: 'Podiam ser mais justos com o esforço do grupo.', effects: { mediaConfidence: -2, squadMorale: 2, supporterConfidence: 1 }, headlineHint: 'técnico pede justiça da imprensa' },
      { id: 'c', label: 'Adoro quando perguntam de futebol, não de novela.', effects: { mediaConfidence: -3, boardConfidence: 1 }, headlineHint: 'técnico critica perguntas sensacionalistas' },
      { id: 'd', label: 'Sem vocês o jogo não chega na casa do torcedor — respeito.', effects: { mediaConfidence: 3, supporterConfidence: 1 }, headlineHint: 'técnico elogia papel da imprensa' },
    ],
  },
  {
    id: 'pre_board_baixa',
    context: 'pre_match',
    weight: 2.2,
    tags: { boardMax: 40 },
    prompt: 'A diretoria parece inquieta. Sente pressão interna?',
    options: [
      { id: 'a', label: 'Alinhados. Discussão interna fica interna.', effects: { boardConfidence: 3, mediaConfidence: -1 }, headlineHint: 'técnico diz alinhamento com a diretoria' },
      { id: 'b', label: 'Pressão faz parte do cargo.', effects: { boardConfidence: 1, mediaConfidence: 1, squadMorale: 1 }, headlineHint: 'técnico normaliza pressão da diretoria' },
      { id: 'c', label: 'Peço paciência e continuidade do projeto.', effects: { boardConfidence: 2, supporterConfidence: -1, mediaConfidence: 1 }, headlineHint: 'técnico pede paciência à diretoria' },
      { id: 'd', label: 'Quem especula demissão está inventando capítulo.', effects: { mediaConfidence: -4, boardConfidence: 1 }, headlineHint: 'técnico nega novela de demissão' },
    ],
  },

  // ═══ REFORÇO RECENTE (últimos 14 dias) ════════════════════════════════════
  {
    id: 'both_reforco_expectativa',
    context: 'both',
    weight: 3.2,
    tags: { requiresRecentSigning: true },
    prompt: 'O reforço recente já é titular absoluto na sua cabeça?',
    options: [
      {
        id: 'a',
        label: 'Ele chega para somar — a vaga se conquista no treino.',
        effects: { targetPlayerMorale: 4, squadMorale: 1, mediaConfidence: 1 },
        headlineHint: 'técnico diz que {{signing}} disputa posição no treino',
      },
      {
        id: 'b',
        label: 'Trouxemos para jogar. Merece confiança imediata.',
        effects: { targetPlayerMorale: 7, squadMorale: -1, supporterConfidence: 3, mediaConfidence: -1 },
        headlineHint: 'técnico banca {{signing}} como peça imediata',
      },
      {
        id: 'c',
        label: 'Sem romantismo: se não render, fica no banco.',
        effects: { targetPlayerMorale: -4, boardConfidence: 3, mediaConfidence: 2 },
        headlineHint: 'técnico cobra rendimento de {{signing}}',
      },
      {
        id: 'd',
        label: 'Não discuto escalação por reforço. Vejo o coletivo.',
        effects: { targetPlayerMorale: 0, squadMorale: 2, mediaConfidence: -2 },
        headlineHint: 'técnico evita elevar {{signing}} acima do grupo',
      },
    ],
  },
  {
    id: 'pre_reforco_adaptacao',
    context: 'pre_match',
    weight: 3,
    tags: { requiresRecentSigning: true },
    prompt: 'Como está a adaptação do reforço recente no CT?',
    options: [
      {
        id: 'a',
        label: 'Rápido: já entendeu a ideia tática.',
        effects: { targetPlayerMorale: 5, boardConfidence: 2, mediaConfidence: 1 },
        headlineHint: 'técnico elogia adaptação de {{signing}}',
      },
      {
        id: 'b',
        label: 'Normal — todo mundo precisa de tempo.',
        effects: { targetPlayerMorale: 2, mediaConfidence: 1 },
        headlineHint: 'técnico pede tempo para {{signing}}',
      },
      {
        id: 'c',
        label: 'Ainda está atrás. Cobrei intensidade.',
        effects: { targetPlayerMorale: -3, boardConfidence: 2, mediaConfidence: 2 },
        headlineHint: 'técnico admite atraso de {{signing}} no CT',
      },
      {
        id: 'd',
        label: 'Detalhe interno. Vocês vão ver em campo.',
        effects: { targetPlayerMorale: 1, mediaConfidence: -3 },
        headlineHint: 'técnico fecha a porta sobre {{signing}}',
      },
    ],
  },
  {
    id: 'post_reforco_estreia',
    context: 'post_match',
    weight: 3.1,
    tags: { requiresRecentSigning: true },
    prompt: 'O reforço recente correspondeu ao que o clube investiu?',
    options: [
      {
        id: 'a',
        label: 'Mostrou personalidade. Caminho certo.',
        effects: { targetPlayerMorale: 6, supporterConfidence: 3, mediaConfidence: 1 },
        headlineHint: 'técnico exalta estreia de {{signing}}',
      },
      {
        id: 'b',
        label: 'Fez o básico. Ainda tem margem enorme.',
        effects: { targetPlayerMorale: 1, boardConfidence: 1, mediaConfidence: 1 },
        headlineHint: 'técnico avalia {{signing}} com cautela',
      },
      {
        id: 'c',
        label: 'Abaixo do esperado — e ele sabe disso.',
        effects: { targetPlayerMorale: -5, supporterConfidence: -1, mediaConfidence: 2 },
        headlineHint: 'técnico cobra {{signing}} após o jogo',
      },
      {
        id: 'd',
        label: 'Um jogo não define contrato. Próximo.',
        effects: { targetPlayerMorale: 2, mediaConfidence: -1 },
        headlineHint: 'técnico protege {{signing}} de julgamento precipitado',
      },
    ],
  },
  {
    id: 'both_reforco_vestiario',
    context: 'both',
    weight: 2.8,
    tags: { requiresRecentSigning: true },
    prompt: 'O grupo acolheu bem o reforço recente?',
    options: [
      {
        id: 'a',
        label: 'Totalmente. Já é um deles no vestiário.',
        effects: { targetPlayerMorale: 5, squadMorale: 3, mediaConfidence: 1 },
        headlineHint: 'técnico diz que {{signing}} foi bem acolhido',
      },
      {
        id: 'b',
        label: 'Há integração natural — sem drama.',
        effects: { targetPlayerMorale: 2, squadMorale: 1 },
        headlineHint: 'técnico descreve integração serena de {{signing}}',
      },
      {
        id: 'c',
        label: 'Alguns precisam aceitar a concorrência. Futebol é assim.',
        effects: { targetPlayerMorale: 3, squadMorale: -2, boardConfidence: 2, mediaConfidence: 1 },
        headlineHint: 'técnico fala em concorrência após chegada de {{signing}}',
      },
      {
        id: 'd',
        label: 'Vestiário não é pauta pública.',
        effects: { targetPlayerMorale: 0, mediaConfidence: -3, squadMorale: 1 },
        headlineHint: 'técnico fecha o vestiário sobre {{signing}}',
      },
    ],
  },
  {
    id: 'pre_reforco_midia',
    context: 'pre_match',
    weight: 2.9,
    tags: { requiresRecentSigning: true },
    prompt: 'A imprensa elevou demais o reforço recente. Isso pesa?',
    options: [
      {
        id: 'a',
        label: 'Ele é forte o bastante para carregar a expectativa.',
        effects: { targetPlayerMorale: 4, supporterConfidence: 2, mediaConfidence: -1 },
        headlineHint: 'técnico banca {{signing}} sob holofote',
      },
      {
        id: 'b',
        label: 'A narrativa de vocês não escala por mim.',
        effects: { targetPlayerMorale: 2, mediaConfidence: -4, squadMorale: 1 },
        headlineHint: 'técnico rebate hype em cima de {{signing}}',
      },
      {
        id: 'c',
        label: 'Peso demais cedo atrapalha. Peço equilíbrio.',
        effects: { targetPlayerMorale: 3, mediaConfidence: 2, supporterConfidence: -1 },
        headlineHint: 'técnico pede equilíbrio na cobertura de {{signing}}',
      },
      {
        id: 'd',
        label: 'Se não aguentar pressão, escolheu o clube errado.',
        effects: { targetPlayerMorale: -6, boardConfidence: 2, mediaConfidence: 1, supporterConfidence: 1 },
        headlineHint: 'técnico endurece discurso com {{signing}}',
      },
    ],
  },
  {
    id: 'post_reforco_banco',
    context: 'post_match',
    weight: 2.7,
    tags: { requiresRecentSigning: true },
    prompt: 'Deixar o reforço recente no banco (ou pouco usado) foi mensagem?',
    options: [
      {
        id: 'a',
        label: 'Foi leitura de jogo, não castigo.',
        effects: { targetPlayerMorale: 2, boardConfidence: 1, mediaConfidence: 1 },
        headlineHint: 'técnico explica uso de {{signing}} sem drama',
      },
      {
        id: 'b',
        label: 'Quem está melhor joga. Ele precisa superar isso.',
        effects: { targetPlayerMorale: -3, squadMorale: 2, mediaConfidence: 2 },
        headlineHint: 'técnico diz que {{signing}} disputa vaga no mérito',
      },
      {
        id: 'c',
        label: 'Proteção: ainda não está no ponto físico.',
        effects: { targetPlayerMorale: 3, mediaConfidence: -1 },
        headlineHint: 'técnico cita proteção física a {{signing}}',
      },
      {
        id: 'd',
        label: 'Próxima pergunta. Escalação é minha.',
        effects: { targetPlayerMorale: -1, mediaConfidence: -4, boardConfidence: 1 },
        headlineHint: 'técnico corta debate sobre {{signing}} na escalação',
        aggressive: true,
      },
    ],
  },

  // ═══ CONVOCAÇÃO (partida importante) ═══════════════════════════════════════
  {
    id: 'callup_lista',
    context: 'callup',
    weight: 3,
    prompt: 'Como montou a lista para este jogo decisivo?',
    options: [
      { id: 'a', label: 'Mérito puro — quem treinou melhor está dentro.', effects: { squadMorale: 4, boardConfidence: 2, mediaConfidence: 2 }, headlineHint: 'técnico cita mérito na convocação' },
      { id: 'b', label: 'Experiência para jogos grandes. Ponto.', effects: { squadMorale: 1, boardConfidence: 3, mediaConfidence: 1 }, headlineHint: 'técnico prioriza experiência na lista' },
      { id: 'c', label: 'Surpresas fazem parte — a imprensa vai ver em campo.', effects: { supporterConfidence: 3, mediaConfidence: -2 }, headlineHint: 'técnico promete surpresas na convocação' },
      { id: 'd', label: 'Não discuto lista com a imprensa.', effects: { mediaConfidence: -4, boardConfidence: 1 }, headlineHint: 'técnico fecha a porta sobre a convocação', aggressive: true },
    ],
  },
  {
    id: 'callup_cortado',
    context: 'callup',
    weight: 2.5,
    prompt: 'Houve nomes importantes de fora. Como explica?',
    options: [
      { id: 'a', label: 'Decisão técnica. Respeito quem ficou de fora.', effects: { squadMorale: 2, mediaConfidence: 1 }, headlineHint: 'técnico respeita os cortados da lista' },
      { id: 'b', label: 'Quem não está 100% não entra em jogo grande.', effects: { boardConfidence: 3, squadMorale: -1, mediaConfidence: 2 }, headlineHint: 'técnico endurece critério físico na convocação' },
      { id: 'c', label: 'Rotatividade — todos terão chance nesta temporada.', effects: { squadMorale: 3, supporterConfidence: 1 }, headlineHint: 'técnico fala em rotatividade na convocação' },
      { id: 'd', label: 'Vocês inventam crise onde não há.', effects: { mediaConfidence: -5, supporterConfidence: -1 }, headlineHint: 'técnico confronta a imprensa sobre cortes', aggressive: true },
    ],
  },
  {
    id: 'callup_pressao',
    context: 'callup',
    weight: 2.2,
    prompt: 'A torcida cobra certos nomes. Isso pesa na convocação?',
    options: [
      { id: 'a', label: 'Ouço a torcida, mas decido eu.', effects: { supporterConfidence: 3, boardConfidence: 2, mediaConfidence: 1 }, headlineHint: 'técnico equilibra cobrança da torcida na lista' },
      { id: 'b', label: 'A lista é técnica, não plebiscito.', effects: { boardConfidence: 4, supporterConfidence: -2, mediaConfidence: 2 }, headlineHint: 'técnico rejeita pressão popular na convocação' },
      { id: 'c', label: 'Quero o que a torcida quer: vencer.', effects: { supporterConfidence: 5, squadMorale: 2, mediaConfidence: -1 }, headlineHint: 'técnico alinha lista ao desejo da torcida' },
      { id: 'd', label: 'Parem de cutucar o elenco com especulação.', effects: { mediaConfidence: -4, squadMorale: 2 }, headlineHint: 'técnico ataca especulação sobre a lista', aggressive: true },
    ],
  },
  {
    id: 'callup_mensagem',
    context: 'callup',
    weight: 2,
    prompt: 'Que mensagem manda ao grupo com esta convocação?',
    options: [
      { id: 'a', label: 'Estamos prontos para a história deste jogo.', effects: { squadMorale: 5, supporterConfidence: 3, mediaConfidence: 1 }, headlineHint: 'técnico motiva o elenco na convocação' },
      { id: 'b', label: 'Foco tático. Sem romantismo.', effects: { boardConfidence: 3, squadMorale: 1, mediaConfidence: 2 }, headlineHint: 'técnico pede frieza na convocação' },
      { id: 'c', label: 'Quem vestir a camisa tem obrigação de entregar.', effects: { squadMorale: -1, boardConfidence: 3, supporterConfidence: 2 }, headlineHint: 'técnico cobra obrigação na convocação' },
      { id: 'd', label: 'Sem mensagem para vocês. É interna.', effects: { mediaConfidence: -3, squadMorale: 1 }, headlineHint: 'técnico reserva mensagem só ao vestiário', aggressive: true },
    ],
  },

  // ═══ LESÃO GRAVE ═══════════════════════════════════════════════════════════
  {
    id: 'injury_estado',
    context: 'injury',
    weight: 3,
    prompt: 'Como está o quadro do atleta lesionado?',
    options: [
      { id: 'a', label: 'Grave, mas o departamento médico conduz bem.', effects: { boardConfidence: 2, mediaConfidence: 2, squadMorale: 1 }, headlineHint: 'técnico atualiza lesão de {{injured}} com cautela' },
      { id: 'b', label: 'Vamos com calma — não há data mágica de retorno.', effects: { mediaConfidence: 1, boardConfidence: 1 }, headlineHint: 'técnico evita prazo para retorno de {{injured}}' },
      { id: 'c', label: 'É um desfalque duro. O grupo precisa cobrir.', effects: { squadMorale: 3, supporterConfidence: 1 }, headlineHint: 'técnico pede cobertura do grupo sem {{injured}}' },
      { id: 'd', label: 'Não vou alimentar especulação médica.', effects: { mediaConfidence: -4 }, headlineHint: 'técnico corta perguntas sobre {{injured}}', aggressive: true },
    ],
  },
  {
    id: 'injury_impacto',
    context: 'injury',
    weight: 2.4,
    prompt: 'Quanto essa lesão muda o planejamento?',
    options: [
      { id: 'a', label: 'Ajustamos o sistema. O time é maior que um nome.', effects: { squadMorale: 4, boardConfidence: 2, mediaConfidence: 1 }, headlineHint: 'técnico diz que o time supera ausência de {{injured}}' },
      { id: 'b', label: 'Perdemos qualidade — sem maquiar.', effects: { boardConfidence: 1, mediaConfidence: 2, supporterConfidence: -1 }, headlineHint: 'técnico admite impacto da lesão de {{injured}}' },
      { id: 'c', label: 'Mercado e base estão no radar se precisar.', effects: { boardConfidence: 3, mediaConfidence: 1 }, headlineHint: 'técnico abre porta a reforço após lesão de {{injured}}' },
      { id: 'd', label: 'Vocês já enterraram a temporada. Ridículo.', effects: { mediaConfidence: -5, supporterConfidence: -2 }, headlineHint: 'técnico explode com a imprensa sobre {{injured}}', aggressive: true },
    ],
  },
  {
    id: 'injury_apoio',
    context: 'injury',
    weight: 2.2,
    prompt: 'O atleta lesionado recebe apoio do grupo e do clube?',
    options: [
      { id: 'a', label: 'Total. Ele não está sozinho nisso.', effects: { squadMorale: 4, mediaConfidence: 2 }, headlineHint: 'técnico garante apoio a {{injured}}' },
      { id: 'b', label: 'Profissionalmente, sim. Drama fica de fora.', effects: { boardConfidence: 2, mediaConfidence: 1 }, headlineHint: 'técnico trata lesão de {{injured}} com frieza profissional' },
      { id: 'c', label: 'Queremos ele de volta o mais rápido possível.', effects: { supporterConfidence: 2, squadMorale: 2, mediaConfidence: 1 }, headlineHint: 'técnico deseja retorno rápido de {{injured}}' },
      { id: 'd', label: 'Vida privada do atleta não é pauta.', effects: { mediaConfidence: -3 }, headlineHint: 'técnico protege privacidade de {{injured}}', aggressive: true },
    ],
  },
  {
    id: 'injury_culpa',
    context: 'injury',
    weight: 1.8,
    prompt: 'Houve sobrecarga ou erro na gestão de carga?',
    options: [
      { id: 'a', label: 'Revisamos tudo. Se errou, corrigimos.', effects: { boardConfidence: 2, mediaConfidence: 2 }, headlineHint: 'técnico admite revisão após lesão de {{injured}}' },
      { id: 'b', label: 'Futebol tem risco. Não caçamos culpados.', effects: { mediaConfidence: 1, squadMorale: 1 }, headlineHint: 'técnico relativiza risco após lesão de {{injured}}' },
      { id: 'c', label: 'O departamento médico tem nossa confiança.', effects: { boardConfidence: 3, mediaConfidence: 1 }, headlineHint: 'técnico respalda médico após lesão de {{injured}}' },
      { id: 'd', label: 'Parem de caçar culpado para manchete.', effects: { mediaConfidence: -5, boardConfidence: -1 }, headlineHint: 'técnico ataca a imprensa por caça a culpados', aggressive: true },
    ],
  },

  // ═══ CRISE FINANCEIRA ══════════════════════════════════════════════════════
  {
    id: 'finance_caixa',
    context: 'finance_crisis',
    weight: 3,
    prompt: 'O caixa do clube preocupa. Como o senhor responde?',
    options: [
      { id: 'a', label: 'Estamos transparentes com a diretoria e ajustando.', effects: { boardConfidence: 4, mediaConfidence: 2 }, headlineHint: 'técnico fala em ajuste financeiro com a diretoria' },
      { id: 'b', label: 'No campo a gente resolve; finanças são da mesa.', effects: { boardConfidence: 1, squadMorale: 2, mediaConfidence: -1 }, headlineHint: 'técnico separa campo e crise financeira' },
      { id: 'c', label: 'A cobrança é justa — precisamos ser eficientes.', effects: { supporterConfidence: 2, boardConfidence: 2, mediaConfidence: 1 }, headlineHint: 'técnico assume pressão financeira' },
      { id: 'd', label: 'Vocês amplificam crise para vender jornal.', effects: { mediaConfidence: -5, boardConfidence: -1 }, headlineHint: 'técnico acusa a imprensa de alarmismo financeiro', aggressive: true },
    ],
  },
  {
    id: 'finance_elenco',
    context: 'finance_crisis',
    weight: 2.5,
    prompt: 'O elenco sente insegurança com a situação financeira?',
    options: [
      { id: 'a', label: 'O grupo está profissional e focado.', effects: { squadMorale: 4, mediaConfidence: 1 }, headlineHint: 'técnico diz que o elenco ignora ruído financeiro' },
      { id: 'b', label: 'Há conversas internas. Protejo o vestiário.', effects: { squadMorale: 2, mediaConfidence: -1, boardConfidence: 1 }, headlineHint: 'técnico protege vestiário na crise financeira' },
      { id: 'c', label: 'Salários e calendário estão sob controle da diretoria.', effects: { boardConfidence: 3, mediaConfidence: 2 }, headlineHint: 'técnico remete salários à diretoria' },
      { id: 'd', label: 'Parem de assustar meus jogadores.', effects: { mediaConfidence: -4, squadMorale: 3 }, headlineHint: 'técnico confronta imprensa por assustar o elenco', aggressive: true },
    ],
  },
  {
    id: 'finance_mercado',
    context: 'finance_crisis',
    weight: 2.2,
    prompt: 'Isso limita o mercado e reforços?',
    options: [
      { id: 'a', label: 'Vamos ser criativos — base, empréstimos, critérios.', effects: { boardConfidence: 3, mediaConfidence: 2, supporterConfidence: 1 }, headlineHint: 'técnico fala em criatividade no mercado sob crise' },
      { id: 'b', label: 'Sem dinheiro fácil. Aceito a realidade.', effects: { boardConfidence: 2, mediaConfidence: 1 }, headlineHint: 'técnico aceita limite financeiro no mercado' },
      { id: 'c', label: 'A torcida quer reforços; cobro soluções na mesa.', effects: { supporterConfidence: 4, boardConfidence: -2, mediaConfidence: 1 }, headlineHint: 'técnico cobra reforços apesar da crise' },
      { id: 'd', label: 'Parem de pedir reforço de R$ 50 mi num artigo.', effects: { mediaConfidence: -4, supporterConfidence: -1 }, headlineHint: 'técnico ironiza pedidos de reforço da imprensa', aggressive: true },
    ],
  },
  {
    id: 'finance_futuro',
    context: 'finance_crisis',
    weight: 2,
    prompt: 'Há risco de cortes ou venda de peças-chave?',
    options: [
      { id: 'a', label: 'Prioridade é estabilidade. Conversamos caso a caso.', effects: { boardConfidence: 3, squadMorale: 1, mediaConfidence: 1 }, headlineHint: 'técnico pede estabilidade diante da crise' },
      { id: 'b', label: 'Se venderem peça-chave, cobro reposição.', effects: { boardConfidence: -1, squadMorale: 2, supporterConfidence: 2 }, headlineHint: 'técnico condiciona vendas a reposição' },
      { id: 'c', label: 'Confio no projeto de médio prazo.', effects: { boardConfidence: 4, mediaConfidence: 2 }, headlineHint: 'técnico endossa projeto em meio à crise' },
      { id: 'd', label: 'Chega de funeral financeiro. Próximo tema.', effects: { mediaConfidence: -5 }, headlineHint: 'técnico encerra pauta financeira com hostilidade', aggressive: true },
    ],
  },

  // ═══ STORY ARC (capítulo narrativo) ════════════════════════════════════════
  {
    id: 'arc_versao',
    context: 'story_arc',
    weight: 3,
    prompt: 'A narrativa do momento explodiu. Qual é a sua versão?',
    options: [
      { id: 'a', label: 'Houve atrito, já estamos alinhando o grupo.', effects: { squadMorale: 3, mediaConfidence: 1, boardConfidence: 2 }, headlineHint: 'técnico admite atrito e fala em alinhamento' },
      { id: 'b', label: 'É barulho externo. Internamente seguimos firmes.', effects: { squadMorale: 2, mediaConfidence: -1, supporterConfidence: 1 }, headlineHint: 'técnico minimiza barulho externo' },
      { id: 'c', label: 'Assumo a responsabilidade e peço foco.', effects: { boardConfidence: 3, mediaConfidence: 2, supporterConfidence: 2 }, headlineHint: 'técnico assume responsabilidade no arco de crise' },
      { id: 'd', label: 'Vocês inventaram um folhetim. Chega.', effects: { mediaConfidence: -5, boardConfidence: -1 }, headlineHint: 'técnico explode com a narrativa da imprensa', aggressive: true },
    ],
  },
  {
    id: 'arc_vestiario',
    context: 'story_arc',
    weight: 2.6,
    prompt: 'O vestiário aguenta essa novela?',
    options: [
      { id: 'a', label: 'O grupo é adulto. Conversamos e seguimos.', effects: { squadMorale: 4, mediaConfidence: 1 }, headlineHint: 'técnico diz que o vestiário superou a novela' },
      { id: 'b', label: 'Protejo o ambiente — sem detalhes públicos.', effects: { squadMorale: 2, mediaConfidence: -2 }, headlineHint: 'técnico fecha o vestiário na crise' },
      { id: 'c', label: 'Quem atrapalhar fica de fora. Simples.', effects: { squadMorale: -2, boardConfidence: 3, mediaConfidence: 1 }, headlineHint: 'técnico ameaça cortes por clima interno' },
      { id: 'd', label: 'Parem de cutucar meus jogadores.', effects: { mediaConfidence: -4, squadMorale: 2 }, headlineHint: 'técnico confronta imprensa por cutucar o elenco', aggressive: true },
    ],
  },
  {
    id: 'arc_virada',
    context: 'story_arc',
    weight: 2.4,
    prompt: 'Como vira essa página?',
    options: [
      { id: 'a', label: 'Em campo. Discurso sem resultado é vazio.', effects: { squadMorale: 3, supporterConfidence: 3, mediaConfidence: 1 }, headlineHint: 'técnico diz que a virada será em campo' },
      { id: 'b', label: 'Com diálogo, trabalho e menos ruído.', effects: { boardConfidence: 2, mediaConfidence: 2, squadMorale: 1 }, headlineHint: 'técnico pede menos ruído para virar a página' },
      { id: 'c', label: 'Aceito a cobrança — ela é parte do cargo.', effects: { boardConfidence: 2, mediaConfidence: 2, supporterConfidence: 1 }, headlineHint: 'técnico aceita cobrança no auge da novela' },
      { id: 'd', label: 'Não alimentem o folhetim. Próximo tema.', effects: { mediaConfidence: -4 }, headlineHint: 'técnico encerra o capítulo com hostilidade', aggressive: true },
    ],
  },
  {
    id: 'arc_diretoria',
    context: 'story_arc',
    weight: 2.2,
    prompt: 'A diretoria acompanha de perto. Há alinhamento?',
    options: [
      { id: 'a', label: 'Total. Estamos na mesma página.', effects: { boardConfidence: 4, mediaConfidence: 1 }, headlineHint: 'técnico afirma alinhamento com a diretoria' },
      { id: 'b', label: 'Há cobrança saudável — e resposta nossa.', effects: { boardConfidence: 2, squadMorale: 1, mediaConfidence: 1 }, headlineHint: 'técnico reconhece cobrança da mesa' },
      { id: 'c', label: 'Preciso de estabilidade para trabalhar.', effects: { boardConfidence: -1, mediaConfidence: 1, supporterConfidence: 1 }, headlineHint: 'técnico pede estabilidade à diretoria' },
      { id: 'd', label: 'Não discuto bastidores com vocês.', effects: { mediaConfidence: -3, boardConfidence: 1 }, headlineHint: 'técnico fecha bastidores da diretoria', aggressive: true },
    ],
  },
];
